### ISSUE TITLE
Opening negative crates gives you more crates

### ISSUE THREAD

**Issue by Gartham** [Gartham/c10ver#60]

**Comment by Gartham** [comment]
Once there's documentation on everything, I'll mark this issue with the **good first issue** label.

**Comment by alwx2008** [comment]
dont worry, this doesnt work anymore.
it returns the issue of "@user you don't have any crates of that type."

**Comment by Gartham** [comment]
I should've specified, but this bug only works when you already have some crates. (Which is another issue.)
