### ISSUE TITLE
Foodstuffs have too high a drop chance

### ISSUE THREAD

**Issue by Gartham** [Gartham/c10ver#61]
Foods don't need to be removed, but their drop rate from crates needs to be severely decreased.

**Comment by alwx2008** [comment]
those three commits are to deal with this issue.

**Comment by alwx2008** [comment]
shouldnt you merge them together and then afterwards this issue would be fixed.

**Comment by alwx2008** [comment]
im thinking it should work

**Comment by Gartham** [comment]
Oh yeah. I wonder if I can merge them into one pull request.

**Comment by Gartham** [comment]
I think I need to switch `>` and `<` (because I think these commits increase the chance of loot drops 👀).

**Comment by Gartham** [comment]
I think I mislabeled this issue. @alwx2008 the drop rates for food from crates was actually already decreased in #66. The reason that this issue was not closed in that pull request must have been due to me thinking that this issue was to reduce the effect of multipliers from foods, not to reduce the chance of food appearing as loot from crates.

I changed the title of this issue to reflect that.
